### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by Djkriz** [StefanNienhuis/homebridge-bold#4]
Since today unlocking Bold is not working anymore for me. 
I deleted my account and generated a new code but that didn’t help either.
Error log:

Error (401) while activating device (5324): Authentication is possible but has failed or not yet been provided.

**Comment by StefanNienhuis** [comment]
I will look into it tomorrow when I have time. In the mean time I think you can restart the authentication process to fix it for now.

**Comment by StefanNienhuis** [comment]
Didn’t read your message properly, recreating the login didn’t work, I’ll look into it soon.

**Comment by StefanNienhuis** [comment]
The problem was caused by a change in the Bold API, which is internal (sort of), which means they don't warn me of breaking changes. This has been resolved in `v1.0.11`.

I will reach out to Bold to see if this plugin can get official API access, so that we can avoid stuff like this.

**Comment by Djkriz** [comment]
I just installed the new version however I still get the same message. Even after generating a new authentication code. Do I do something wrong?

**Comment by StefanNienhuis** [comment]
I might've accidentally swapped tokens while testing, but version v1.0.12 should really fix this.

**Comment by benhumphry** [comment]
I've experienced the same problem since yesterday. v1.0.11 and v1.0.12 have both given the same issue.
![Screenshot_20220303-145754](https://user-images.githubusercontent.com/57911087/156591562-4c6a621c-47c9-4f84-8fc3-71e25042eed9.png)

I've deleted the key and reauthenticated several times.

**Comment by Djkriz** [comment]
Unfortunately still the same issue with 1.0.12.

**Comment by StefanNienhuis** [comment]
Could you try logging in using this? https://stefannienhuis.github.io/homebridge-bold/

**Comment by Djkriz** [comment]
> Could you try logging in using this? https://stefannienhuis.github.io/homebridge-bold/

I can login using that site and I also get an authentication code.

**Comment by benhumphry** [comment]
Same here. Logs in and generates a key. When I update the plug-in with this key (and restart Homebridge), I still get the same authentication error when I try to trigger the unlock action.

**Comment by StefanNienhuis** [comment]
Okay, latest release should finally fix this. It was a problem with the refreshing of the token on startup, which hadn't been updated yet.

**Comment by Djkriz** [comment]
It works again! Thanks!

**Comment by benhumphry** [comment]
Thank you!
